---
title: "Reproducible Research: Peer Assessment 1"
author: 'Atharva Rmagirkar'
date: 'July 7th, 2020'
output: 
  html_document:
    keep_md: true
---



#### load the necessary libraries

```{r load_lib,echo=TRUE,cache=TRUE}
library(plyr)
library(ggplot2)
```

-------------------

## Loading and preprocessing the data

```{r load_process,echo=TRUE,cache=TRUE}
unzip(zipfile = "activity.zip", exdir = ".")
activity <- read.csv(file = "activity.csv", header = TRUE)
activity$date<-as.Date(x = activity$date, format = "%Y-%m-%d")
```

------------------------

## What is mean total number of steps taken per day?

```{r meansteps,echo=TRUE,cache=TRUE}
Perday<-ddply(activity,
              .(date),
              summarize,
              totalsteps=sum(steps))
qplot(Perday$totalsteps,
                binwidth=1000,
                geom = "histogram",
                xlab = "total number of steps",
                ylab = "frequency",
                main = "Total steps daily before replacing NA values")

```

#### the Mean and the Median are:-

```{r mean_median_display,echo=TRUE,cache=TRUE}
mean(Perday$totalsteps,na.rm = TRUE)
median(Perday$totalsteps,na.rm = TRUE)
```

--------------------

## What is the average daily activity pattern?

```{r interval_avgsteps,echo=TRUE,cache=TRUE}
interval_avg <- ddply(activity,
                      .(interval),
                      summarize,
                      avgsteps=mean(steps,
                                    na.rm = TRUE))

plot(x = interval_avg$interval,
               y = interval_avg$avgsteps,
               type = "l")

```

--------------------

## Imputing missing values

#### First check the number of missing values

```{r check_missing,echo=TRUE,cache=TRUE}
print("total number of missing values are:-")
sum(is.na(activity$steps))
```

```{r missing_vals,echo=TRUE,cache=TRUE}

int_avgs<-rep(interval_avg$avgsteps,length(activity$steps)/length(interval_avg$interval))
activity$avgs<-int_avgs
inputNas= function(steps, avgs) 
{
  if (is.na(steps)) 
  { 
    return(avgs)
  }
  return(steps)
}


filled_data = activity
filled_data$steps = mapply(inputNas,
                           filled_data$steps,
                           filled_data$avgs)

```

#### Check the number of missing values again

```{r recheck_missing,echo=TRUE,cache=TRUE}

print("total number of missing values are:-")
sum(is.na(filled_data$steps))

```

#### Make a histogram without any missing values 

```{r plot_without_missing,echo=TRUE,cache=TRUE}
perday.filled<-ddply(filled_data,.(date),summarize,totalsteps=sum(steps))
qplot(perday.filled$totalsteps,
                  binwidth=1000,
                  geom = "histogram",
                  xlab = "total number of steps",
                  ylab = "frequency",
                  main = "Total steps daily after replacing NA values")


```

-------------------

## Are there differences in activity patterns between weekdays and weekends?

```{r week_days,echo=TRUE,cache=TRUE}

which_day<-function(day)
  {
  
    if(day %in% c("Monday","Tuesday","Wednesday","Thursday","Friday"))
      {
        return("Weekday")
      }
    else if(day %in% c("Saturday","Sunday"))
      {
        return("Weekend")
      }
    else
      {
        stop("Invalid Day")
      }

  }

activity$week<-sapply(X = weekdays(activity$date),FUN = which_day,simplify = TRUE)
filled_data$week<-activity$week

interval_avg.filled<-ddply(filled_data,.(interval,week),summarise,totalsteps=mean(steps))

ggplot(interval_avg.filled, aes(interval, totalsteps)) + geom_line() + facet_grid(week ~ .) + xlab("5 minute interval") + ylab("total steps")  


```

------------
